name: Create GitHub Releases

on:
  push:
    tags:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Load Release Informations
      run: |
        title=`cat github-releases/title.txt`
        echo "TITLE=${title}" >> $GITHUB_ENV

    - name: Install Zip
      uses: montudor/action-zip@v1

    - name: Zip .NET Release
      run: zip -qq -r "CSVParser-dotnet.zip" .
      working-directory: "CSV Parser/src/"

    - name: Listing files for .unitypackage
      run: |
        cd "Unity Examples/CSV Parser Example 2018.4/"
        echo "Assets/CSVParser.meta" > metaListOld
        find "Assets/CSVParser/" -name \*.meta > metaListOld
        cd "../../Unity Examples/CSV Parser Example 2021.2/"
        echo "Assets/CSVParser.meta" > metaListNew
        find "Assets/CSVParser/" -name \*.meta > metaListNew
        cd /

    - name: Create .unitypackage for old Unity
      uses: pCYSl5EDgo/create-unitypackage@v1
      with:
       # Output unitypackage file path
       package-path: "Unity Examples/CSV Parser Example 2018.4/CSVParser-Unity2021.1OrOlder.unitypackage"
       include-files: "Unity Examples/CSV Parser Example 2018.4/metaListOld"
       project-folder: "Unity Examples/CSV Parser Example 2018.4/"

    - name: Create .unitypackage for new Unity
      uses: pCYSl5EDgo/create-unitypackage@v1
      with:
       # Output unitypackage file path
       package-path: "Unity Examples/CSV Parser Example 2021.2/CSVParser-Unity2021.2OrNewer.unitypackage"
       include-files: "Unity Examples/CSV Parser Example 2021.2/metaListNew"
       project-folder: "Unity Examples/CSV Parser Example 2021.2/"

    - name: Create a GitHub Release
      uses: softprops/action-gh-release@v0.1.5
      with:
        # Note-worthy description of changes in release
#         body: # optional
        # Path to load note-worthy description of changes in release from
        body_path: github-releases/body.md
        # Gives the release a custom name. Defaults to tag name
        name: ${{ env.TITLE }}
        # Creates a draft release. Defaults to false
        draft: false
        # Identify the release as a prerelease. Defaults to false
        prerelease: false
        # Newline-delimited list of path globs for asset files to upload
        files: |
          CSV Parser/src/CSVParser-dotnet.zip
          Unity Examples/CSV Parser Example 2018.4/CSVParser-Unity2021.1OrOlder.unitypackage
          Unity Examples/CSV Parser Example 2021.2/CSVParser-Unity2021.2OrNewer.unitypackage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
