name: Create GitHub Releases

on:
  push:
    tags:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Load Release Informations
      run: |
        title=`cat github-releases/title.txt`
        echo "TITLE=${title}" >> $GITHUB_ENV

    - name: Install Zip
      uses: montudor/action-zip@v1

    - name: Zip .NET Release
      run: zip -qq -r "CSV Parser-dotnet.zip" .
      working-directory: "CSV Parser/src/"

    - name: Listing files for .unitypackage
      run: |
        find "Unity Examples/CSV Parser Example 2018.4/Assets/" -name \*.meta > metaListOld
        find "Unity Examples/CSV Parser Example 2021.2/Assets/" -name \*.meta > metaListNew

    - name: Create .unitypackage for old Unity
      uses: pCYSl5EDgo/create-unitypackage@v1
      with:
       # Output unitypackage file path
       package-path: "CSVParser-Unity2021.1OrOlder.unitypackage"
       include-files: metaListOld

    - name: Create .unitypackage for new Unity
      uses: pCYSl5EDgo/create-unitypackage@v1
      with:
       # Output unitypackage file path
       package-path: "CSVParser-Unity2021.2OrNewer.unitypackage"
       include-files: metaListNew

    - name: Create a GitHub Release
      uses: softprops/action-gh-release@v0.1.5
      with:
        # Note-worthy description of changes in release
#         body: # optional
        # Path to load note-worthy description of changes in release from
        body_path: github-releases/body.md
        # Gives the release a custom name. Defaults to tag name
        name: ${{ env.TITLE }}
        # Creates a draft release. Defaults to false
        draft: false
        # Identify the release as a prerelease. Defaults to false
        prerelease: false
        # Newline-delimited list of path globs for asset files to upload
        files: |
          CSV Parser/src/CSV Parser-dotnet.zip
          CSVParser-Unity2021.1OrOlder.unitypackage
          CSVParser-Unity2021.2OrNewer.unitypackage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
